services:
  app:
    build: .
    container_name: integrated_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      app_network: # <-- Явно вказуємо мережу тут
        # Можна не вказувати IP для app, він отримає динамічно
        # з підмережі, визначеної нижче
    environment:
      - HW_SIMULATOR_ADDRESS=http://az_simulator:8080
    depends_on:
      - az_simulator
      - logstash
    logging:
      driver: "gelf"
      options:
        # --- ЗМІНИ ТУТ: Використовуємо статичну IP Logstash ---
        gelf-address: "udp://172.28.1.1:12201" # <-- ВКАЖІТЬ СТАТИЧНУ IP
        # --- Кінець змін ---
        tag: "integrated_app"

  az_simulator:
    image: alpine:latest
    container_name: az_simulator
    command: sh -c "echo 'Simulating HW...' && sleep infinity"
    restart: unless-stopped
    networks:
      app_network: # <-- Явно вказуємо мережу
        # IP для симулятора (опціонально)
        # ipv4_address: 172.28.1.2

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      # ... решта command ...
    networks:
      app_network: # <-- Явно вказуємо мережу

  grafana:
    image: grafana/grafana:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      app_network: # <-- Явно вказуємо мережу

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      # ... решта environment ...
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      app_network: # <-- Явно вказуємо мережу

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.5
    container_name: logstash
    restart: unless-stopped
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    # --- ЗМІНИ ТУТ: Призначаємо статичну IP для Logstash ---
    networks:
      app_network:
        ipv4_address: 172.28.1.1 # <-- СТАТИЧНА IP ДЛЯ LOGSTASH
    # --- Кінець змін ---

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      app_network: # <-- Явно вказуємо мережу

# --- ЗМІНИ ТУТ: Конфігуруємо мережу з IPAM ---
networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 # Визначаємо підмережу для нашої мережі
          gateway: 172.28.0.1
# --- Кінець змін ---

volumes:
  prometheus_data:
  grafana_data:
  elasticsearch_data: